"""Quick numpy-only oracle probe for smoothed-derivative candidates.

Goal: before retraining the selector, check whether candidates generated by
polynomial / Savitzky-Golay smoothing on the full 11 observations actually
pull the candidate-bank oracle hit-rate above the current 0.7188.

Outputs a compact table:
  - Per new candidate: standalone hit@1cm + complementarity vs existing 27
  - Combined oracle if we add the candidate to the existing bank
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

# Make src importable so we reuse the exact candidate generator the selector saw.
HERE = Path(__file__).resolve()
ROOT = HERE.parent.parent
sys.path.insert(0, str(ROOT / "src"))

import pipeline as P  # noqa: E402  (sets up CANDIDATES + helpers)


R_HIT = P.R_HIT
EPS = P.EPS


# ---------- candidate proposals --------------------------------------------------

# Observation grid: indices 0..10 correspond to timesteps -400..0 ms at 40 ms spacing.
# Target timestep is +80 ms = index 12 (2 steps past the last observation).
T_OBS = np.arange(11, dtype=np.float64)          # 0..10
T_TARGET = 12.0                                   # +80 ms past last obs


def polyfit_extrapolate(x: np.ndarray, indices: np.ndarray, degree: int, target: float) -> np.ndarray:
    """Per-axis LSQ polynomial fit, return value at target index. x: (N,L,3)."""
    idx_int = indices.astype(np.int64)
    idx_float = indices.astype(np.float64)
    sub = x[:, idx_int]                                       # (N, k, 3)
    # Vandermonde once: (k, degree+1)
    V = np.vander(idx_float, N=degree + 1, increasing=True)
    # Solve A @ coeffs = sub for each (n, axis):  A is (k, deg+1), targets (N,k,3)
    # Use lstsq once with batched rhs via reshape.
    sub_flat = sub.transpose(1, 0, 2).reshape(len(idx_int), -1)   # (k, N*3)
    coeffs, *_ = np.linalg.lstsq(V, sub_flat, rcond=None)         # (deg+1, N*3)
    powers = np.asarray([target ** d for d in range(degree + 1)])
    extrap_flat = powers @ coeffs                                  # (N*3,)
    return extrap_flat.reshape(x.shape[0], 3).astype(np.float32)


def weighted_polyfit_extrapolate(
    x: np.ndarray,
    indices: np.ndarray,
    degree: int,
    target: float,
    weights: np.ndarray,
) -> np.ndarray:
    """LSQ poly with per-time weights (last point heavier)."""
    idx_int = indices.astype(np.int64)
    idx_float = indices.astype(np.float64)
    sub = x[:, idx_int]                              # (N, k, 3)
    V = np.vander(idx_float, N=degree + 1, increasing=True)
    W = np.diag(np.sqrt(weights))
    Vw = W @ V                                       # (k, deg+1)
    sub_flat = sub.transpose(1, 0, 2).reshape(len(idx_int), -1)
    sub_w = W @ sub_flat
    coeffs, *_ = np.linalg.lstsq(Vw, sub_w, rcond=None)
    powers = np.asarray([target ** d for d in range(degree + 1)])
    extrap_flat = powers @ coeffs
    return extrap_flat.reshape(x.shape[0], 3).astype(np.float32)


def savgol_extrapolate(x: np.ndarray, window: int, degree: int, target: float) -> np.ndarray:
    """Savitzky-Golay-style: fit poly of given degree to last `window` points,
    evaluate the same poly at `target` (which is past the window)."""
    idx = np.arange(11 - window, 11, dtype=np.float64)
    return polyfit_extrapolate(x, idx, degree, target)


def build_proposals(x: np.ndarray) -> dict[str, np.ndarray]:
    """Return a dict name -> (N,3) predicted xyz at T_TARGET."""
    out: dict[str, np.ndarray] = {}

    # 1) Full-window quadratic / cubic
    out["poly2_all11"] = polyfit_extrapolate(x, T_OBS, 2, T_TARGET)
    out["poly3_all11"] = polyfit_extrapolate(x, T_OBS, 3, T_TARGET)

    # 2) Recent-window polys
    out["poly2_last6"] = savgol_extrapolate(x, window=6, degree=2, target=T_TARGET)
    out["poly2_last8"] = savgol_extrapolate(x, window=8, degree=2, target=T_TARGET)
    out["poly3_last8"] = savgol_extrapolate(x, window=8, degree=3, target=T_TARGET)
    out["poly2_last5"] = savgol_extrapolate(x, window=5, degree=2, target=T_TARGET)
    out["poly1_last5"] = savgol_extrapolate(x, window=5, degree=1, target=T_TARGET)
    out["poly1_last4"] = savgol_extrapolate(x, window=4, degree=1, target=T_TARGET)

    # 3) Recency-weighted polys (heavier weight on later points)
    w_exp = np.exp(0.30 * (T_OBS - T_OBS[-1]))               # last point weight 1.0
    out["wpoly2_all11_exp"] = weighted_polyfit_extrapolate(x, T_OBS, 2, T_TARGET, w_exp)
    out["wpoly3_all11_exp"] = weighted_polyfit_extrapolate(x, T_OBS, 3, T_TARGET, w_exp)

    # 4) Blends: average of two windows (denoise vs locality)
    out["poly2_blend6_11"] = 0.5 * (out["poly2_last6"] + out["poly2_all11"])
    out["poly3_blend8_11"] = 0.5 * (out["poly3_last8"] + out["poly3_all11"])

    # 5) Smoothed-coordinate then frenet-style:
    # Refit poly3 over the full window, *evaluate at every t* to get smoothed coords,
    # then run motion_terms on the smoothed array. This produces "denoised d1/acc"
    # candidates analogous to current frenet_best but using smoothed derivatives.
    smoothed = smooth_full_poly3(x)
    sx = smoothed
    p0_s, d1_s, acc_s = motion_terms_smoothed(sx)
    tangent_s = d1_s / (np.linalg.norm(d1_s, axis=1, keepdims=True) + EPS)
    acc_par_s = np.sum(acc_s * tangent_s, axis=1, keepdims=True) * tangent_s
    acc_perp_s = acc_s - acc_par_s

    # horizon=2 v_scale = 1.0, acc_scale = 1.0
    # frenet_best mimic: d1=1.98, par=0.96, perp=-0.08 (but with SMOOTHED terms)
    out["smooth_frenet_best"] = (
        p0_s + 1.98 * d1_s + 0.96 * acc_par_s + (-0.08) * acc_perp_s
    ).astype(np.float32)

    # par=1.0, perp=0 with smoothed: pure "stay on course"
    out["smooth_par100_perp000"] = (
        p0_s + 1.98 * d1_s + 1.00 * acc_par_s
    ).astype(np.float32)

    return out


def smooth_full_poly3(x: np.ndarray) -> np.ndarray:
    """Refit cubic poly over all 11 points per-axis, evaluate at every original t.
    This produces smoothed coordinates; pass through motion_terms after."""
    V = np.vander(T_OBS, N=4, increasing=True)
    flat = x.transpose(1, 0, 2).reshape(11, -1)         # (11, N*3)
    coeffs, *_ = np.linalg.lstsq(V, flat, rcond=None)   # (4, N*3)
    smoothed_flat = V @ coeffs                           # (11, N*3)
    return smoothed_flat.reshape(11, x.shape[0], 3).transpose(1, 0, 2).astype(np.float32)


def motion_terms_smoothed(sx: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    end_idx = 10
    p0 = sx[:, end_idx]
    d1 = sx[:, end_idx] - sx[:, end_idx - 1]
    d2 = sx[:, end_idx - 1] - sx[:, end_idx - 2]
    acc = d1 - d2
    return p0, d1, acc


# ---------- evaluation helpers ---------------------------------------------------


def hit_rate(pred: np.ndarray, true: np.ndarray) -> float:
    err = np.linalg.norm(pred - true, axis=1)
    return float(np.mean(err <= R_HIT))


def oracle_hit(bank: np.ndarray, true: np.ndarray) -> float:
    """bank: (N, K, 3). Returns fraction of rows with at least one within 1cm."""
    err = np.linalg.norm(bank - true[:, None, :], axis=2)
    return float(np.mean(np.min(err, axis=1) <= R_HIT))


def main() -> None:
    data_root = P.DATA_ROOT
    print(f"data root: {data_root}")
    train_ids, train_y = P.read_labels(data_root / "train_labels.csv")
    train_x = P.load_stack(data_root / "train", train_ids)
    print(f"train_x shape: {train_x.shape}, labels: {train_y.shape}")
    assert train_x.shape[1] == 11, "expected 11-step trajectories"

    # Existing 27-candidate bank
    base_bank = P.make_candidates(train_x, end_idx=10, horizon=2)            # (N, 27, 3)
    base_oracle = oracle_hit(base_bank, train_y)
    print(f"base 27-cand oracle hit@1cm: {base_oracle:.4f}")

    proposals = build_proposals(train_x)

    # Show per-candidate hit
    print("\nPer-proposal standalone hit and gain when added to base bank:")
    print(f"  {'name':<24} {'hit':>7} {'best_when_top':>14} {'oracle_with':>13}  delta")
    rows = []
    for name, pred in proposals.items():
        h = hit_rate(pred, train_y)
        # Add proposal to bank, check new oracle
        extended = np.concatenate([base_bank, pred[:, None, :]], axis=1)
        new_oracle = oracle_hit(extended, train_y)
        # How often this proposal is the unique closest (no existing cand within 1cm but proposal is)
        err_base = np.linalg.norm(base_bank - train_y[:, None, :], axis=2)
        err_new = np.linalg.norm(pred - train_y, axis=1)
        base_miss = np.min(err_base, axis=1) > R_HIT
        new_hit_only = base_miss & (err_new <= R_HIT)
        unique_save = float(np.mean(new_hit_only))
        delta = new_oracle - base_oracle
        rows.append((name, h, unique_save, new_oracle, delta))
        print(f"  {name:<24} {h:>7.4f} {unique_save:>14.4f} {new_oracle:>13.4f}  +{delta:.4f}")

    # Combined: add all proposals at once
    all_extra = np.stack(list(proposals.values()), axis=1)                   # (N, M, 3)
    combined = np.concatenate([base_bank, all_extra], axis=1)
    print(f"\nAll proposals combined ({all_extra.shape[1]} new): oracle {oracle_hit(combined, train_y):.4f}")

    # Best-K combined (greedy): pick proposals whose unique_save is highest, add cumulatively
    rows_sorted = sorted(rows, key=lambda r: r[2], reverse=True)
    print("\nGreedy-add by unique_save:")
    extended = base_bank.copy()
    for i, (name, h, us, o_with, _) in enumerate(rows_sorted, 1):
        pred = proposals[name]
        extended = np.concatenate([extended, pred[:, None, :]], axis=1)
        print(f"  +{i:>2} {name:<24} cumulative oracle={oracle_hit(extended, train_y):.4f} (cand count={extended.shape[1]})")


if __name__ == "__main__":
    main()
